export interface Variant {
  id: string;
  name: string;
  otr: number;
  rebate: number;
  engine: string;
  transmission: string;
  power: number;
  torque: number;
  seats: number;
  fuelType: string;
  promo?: string;
}

export interface Model {
  id: string;
  name: string;
  tagline: string;
  category: string;
  image: string;
  url: string;
  variants: Variant[];
  startingPrice: number;
  interestRate: number;
}

export const models: Model[] = [
  {
    id: "saga",
    name: "Proton Saga",
    tagline: "Intelligence that Thrills",
    category: "B-Segment Sedan",
    image: "/images/proton/saga.png",
    url: "https://www.proton.com/models/all-new-saga",
    startingPrice: 42003.10,
    interestRate: 3.0,
    variants: [
      {
        id: "saga-standard",
        name: "1.5 Standard",
        otr: 42003.10,
        rebate: 500,
        engine: "1.5L i-GT",
        transmission: "Automatic",
        power: 120,
        torque: 150,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "saga-executive",
        name: "1.5 Executive",
        otr: 48121.49,
        rebate: 500,
        engine: "1.5L i-GT",
        transmission: "Automatic",
        power: 120,
        torque: 150,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "saga-premium",
        name: "1.5 Premium",
        otr: 53220.15,
        rebate: 500,
        engine: "1.5L i-GT",
        transmission: "CVT",
        power: 120,
        torque: 150,
        seats: 5,
        fuelType: "Petrol",
      },
    ],
  },
  {
    id: "persona",
    name: "Proton Persona",
    tagline: "Intelligence that Cares",
    category: "B-Segment Sedan",
    image: "/images/proton/persona.png",
    url: "https://www.proton.com/models/persona",
    startingPrice: 50990.69,
    interestRate: 3.0,
    variants: [
      {
        id: "persona-standard",
        name: "1.6 Standard",
        otr: 50990.69,
        rebate: 2000,
        engine: "1.6L VVT",
        transmission: "CVT",
        power: 108,
        torque: 150,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "persona-executive",
        name: "1.6 Executive",
        otr: 56589.35,
        rebate: 2000,
        engine: "1.6L VVT",
        transmission: "CVT",
        power: 108,
        torque: 150,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "persona-premium",
        name: "1.6 Premium",
        otr: 61668.00,
        rebate: 2000,
        engine: "1.6L VVT",
        transmission: "CVT",
        power: 108,
        torque: 150,
        seats: 5,
        fuelType: "Petrol",
      },
    ],
  },
  {
    id: "s70",
    name: "Proton S70",
    tagline: "Intelligence that Evolves",
    category: "C-Segment Sedan",
    image: "/images/proton/s70.png",
    url: "https://www.proton.com/models/s70",
    startingPrice: 77503.71,
    interestRate: 2.65,
    variants: [
      {
        id: "s70-executive",
        name: "1.5T Executive",
        otr: 77503.71,
        rebate: 5000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "s70-premium",
        name: "1.5T Premium",
        otr: 83622.10,
        rebate: 5000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "s70-flagship",
        name: "1.5T Flagship",
        otr: 93819.07,
        rebate: 5000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "s70-flagship-x",
        name: "1.5T Flagship X",
        otr: 98918.07,
        rebate: 5000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
      },
    ],
  },
  {
    id: "x50",
    name: "Proton X50",
    tagline: "Intelligence that Amazes",
    category: "B-Segment SUV",
    image: "/images/proton/x50.png",
    url: "https://www.proton.com/models/all-new-x50",
    startingPrice: 93819.42,
    interestRate: 2.5,
    variants: [
      {
        id: "x50-executive",
        name: "1.5T Executive",
        otr: 93819.42,
        rebate: 5000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "x50-premium",
        name: "1.5T Premium",
        otr: 106056.19,
        rebate: 5000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
        promo: "Free Service 2 Tahun",
      },
      {
        id: "x50-flagship",
        name: "1.5T Flagship",
        otr: 117773.24,
        rebate: 7000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
        promo: "Free Service 2 Tahun",
      },
    ],
  },
  {
    id: "x70",
    name: "Proton X70",
    tagline: "Intelligence that Inspires",
    category: "C-Segment SUV",
    image: "/images/proton/x70.png",
    url: "https://www.proton.com/models/x70",
    startingPrice: 111155.84,
    interestRate: 2.3,
    variants: [
      {
        id: "x70-executive",
        name: "1.5T Executive",
        otr: 111155.84,
        rebate: 7000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
      },
      {
        id: "x70-premium",
        name: "1.5T Premium",
        otr: 124411.36,
        rebate: 7000,
        engine: "1.5L Turbo",
        transmission: "7DCT",
        power: 181,
        torque: 290,
        seats: 5,
        fuelType: "Petrol",
        promo: "Free Service 2 Tahun",
      },
    ],
  },
  {
    id: "x90",
    name: "Proton X90",
    tagline: "Intelligence that Empowers",
    category: "7-Seater SUV",
    image: "/images/proton/x90.png",
    url: "https://www.proton.com/models/x90",
    startingPrice: 111154.85,
    interestRate: 2.3,
    variants: [
      {
        id: "x90-lite",
        name: "1.5T Lite",
        otr: 111154.85,
        rebate: 7000,
        engine: "1.5L Turbo MHEV",
        transmission: "7DCT",
        power: 178,
        torque: 290,
        seats: 7,
        fuelType: "Petrol MHEV",
      },
      {
        id: "x90-prime",
        name: "1.5T Prime",
        otr: 121352.17,
        rebate: 7000,
        engine: "1.5L Turbo MHEV",
        transmission: "7DCT",
        power: 178,
        torque: 290,
        seats: 7,
        fuelType: "Petrol MHEV",
      },
      {
        id: "x90-prime-x",
        name: "1.5T Prime X",
        otr: 127470.56,
        rebate: 7000,
        engine: "1.5L Turbo MHEV",
        transmission: "7DCT",
        power: 178,
        torque: 290,
        seats: 7,
        fuelType: "Petrol MHEV",
      },
    ],
  },
];
